### ISSUE TITLE
Make the project compatible with Python 3

### ISSUE THREAD

**Issue by bodiroga** [Tknika/serial2tcp-gateway#2]
- Ensure that Python 3 is installed in the system
- Install python3-pip
- Install python3 compatible libraries
- Ensure that the program works correctly with python3

**Comment by gersilex** [comment]
I would happily like to contribute by doing this. Do you plan to let the python 3 version co-exist with the python 2 version or replace python 2 altogether? It isn't supported much longer, anyways.

**Comment by bodiroga** [comment]
Hi Leroy! (@gersilex)

I'm glad to see that you like the program and that you are interested in contributing to it, awesome! :+1: 

My original idea was make the project compatible with Python 3 and don't bother supporting Python 2, as it will not be supported after 01/01/2020. We need to force the transition as soon as possible, so, bye bye Python 2!

I was planning to implement the changes in the following weeks, but any PR will be greatly appreciated, sure! If you also have any suggestion or idea, please, go ahead and open an issue to discuss about it :wink: 

Many thanks for your interest and best regards,

Aitor

**Comment by gersilex** [comment]
>bye bye Python 2!
Just what I thought.

>I was planning to implement the changes in the following weeks
That's about the time I thought about doing it. I am currently setting up different environments to test against this software (Windows, Raspberry Pi, Container on amd64 - although there shouldn't be any differences).

I will definitely write here as soon as I start with porting it to Python 3 so that we don't do the work twice. While developing, I am pretty sure some thoughts and ideas will come up and I will create new issues for these on GitHub. :)

**Comment by bodiroga** [comment]
The program relies on udev (through the pyudev library), so I don't think it will work on Windows, sorry :cry:

Looking forward to reading your suggestions!

**Comment by gersilex** [comment]
Starting now in https://github.com/gersilex/serial2tcp-gateway
